package com.evsuite.hardware.catalog

import com.evsuite.hardware.FirmwareGen
import com.evsuite.hardware.FirmwareSupport
import com.evsuite.hardware.R
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Writes `docs/catalogue.md`: every condition and every action the apps actually carry.
 *
 * The list is generated for the same reason the firmware matrix is. A hand-written catalogue
 * drifts the first time an entry is added — and it drifted: the published one still promised
 * an "AM or FM" tune action months after DAB was reachable, and named none of the twenty
 * entries added after it was written. Rendering it from the enums makes that impossible.
 *
 * Labels are resource ids, which the JVM has no resource table for, so the names come back
 * through `R.string` by reflection and the English text out of the `values/` file. That is
 * the same text the car shows on its default locale, which is what a reader of the docs is
 * trying to match against their screen.
 */
class CatalogueDocTest {

    /** Column order, and the wording, of the firmware column. */
    private val columns = listOf(
        FirmwareGen.SWI133, FirmwareGen.SWI68, FirmwareGen.SWI165,
        FirmwareGen.SWI69, FirmwareGen.SWI131, FirmwareGen.SWI132
    )

    /** Resource id → resource name, from the generated `R.string` class. */
    private val resourceNames: Map<Int, String> = R.string::class.java.fields
        .filter { it.type == Int::class.javaPrimitiveType }
        .associate { (it.get(null) as Int) to it.name }

    /** Resource name → English text, from the file the library ships as its default locale. */
    private val strings: Map<String, String> = File("src/main/res/values/strings.xml")
        .readText()
        .let { Regex("""<string name="([^"]+)"[^>]*>(.*?)</string>""", RegexOption.DOT_MATCHES_ALL).findAll(it) }
        .associate { it.groupValues[1] to it.groupValues[2].unescape() }

    private fun String.unescape(): String = replace("&amp;", "&")
        .replace("&lt;", "<").replace("&gt;", ">")
        .replace("&#8230;", "…").replace("\\'", "'")
        .replace(Regex("\\s+"), " ").trim()

    private fun label(res: Int): String = strings[resourceNames[res]] ?: "?"

    /** What the user is asked for, in words rather than in the enum's own vocabulary. */
    private fun value(spec: ValueSpec): String {
        val unit = spec.unitRes.takeIf { it != 0 }?.let { " " + label(it) }.orEmpty()
        return when (spec.kind) {
            ValueKind.NONE -> "—"
            ValueKind.BOOL -> "on / off"
            ValueKind.NUMBER -> if (spec.max >= 0) "${spec.min}…${spec.max}$unit" else "0…max$unit"
            // FIRMWARE_GEN is the one list the catalogue does not hold: the editor fills it
            // from the generations the library knows, so there is nothing to print here.
            ValueKind.ENUM -> spec.options.joinToString(", ") { label(it.labelRes) }
                .ifEmpty { "a list the app fills in" }
            ValueKind.RADIO ->
                "band (" + spec.options.joinToString(", ") { label(it.labelRes) } + "), frequency, play"
            ValueKind.TIME -> "a time of day"
            ValueKind.TIME_RANGE -> "a start and an end time"
            ValueKind.DAYS -> "weekdays"
            ValueKind.DATE -> "a calendar date"
            ValueKind.BT_DEVICE -> "a paired phone"
            ValueKind.PROFILE -> "an EVProfile profile"
            ValueKind.RULE -> "one of your rules"
            ValueKind.APP -> "an installed app"
            ValueKind.CONTACT -> "a number or a contact"
            ValueKind.SMS -> "a number or a contact, and a message"
            ValueKind.TEXT -> "free text"
            ValueKind.CONFIRM -> "a question, and how long to wait"
            ValueKind.DESTINATION -> "an address or coordinates"
            ValueKind.LOCATION -> "a point and a radius" + unit.trim().let { if (it.isEmpty()) "" else " ($it)" }
            ValueKind.WEBHOOK -> "a URL, and an optional body"
            ValueKind.PHYSICAL_BUTTON -> "a button, short or long press"
        }
    }

    /** The generations an entry is annotated for; "any" when it depends on no firmware. */
    private fun firmware(gens: Set<FirmwareGen>?): String = when (gens) {
        null -> "any"
        else -> columns.filter { it in gens }.joinToString(", ") { it.name }.ifEmpty { "none" }
    }

    private fun render(): String = buildString {
        appendLine("<!-- GENERATED by CatalogueDocTest; do not edit by hand. -->")
        appendLine()
        appendLine("# The EVTasker catalogue")
        appendLine()
        appendLine(
            "Every condition a rule can test and every action it can run, straight out of " +
                "`ConditionType` and `ActionType`. *Firmware* is what the entry is annotated " +
                "for; \"any\" means it depends on no vehicle firmware at all, not that it needs " +
                "nothing — a notification still needs the permission, a call still needs a " +
                "paired phone. The car's own Diagnostic screen stays the only answer for the " +
                "car in front of you."
        )
        appendLine()
        appendLine("## Conditions")
        ConditionGroup.entries.forEach { group ->
            val entries = ConditionType.entries.filter { it.group == group }
            if (entries.isEmpty()) return@forEach
            appendLine()
            appendLine("### ${label(group.labelRes)}")
            appendLine()
            appendLine("| Condition | Entry | Tested against | Firmware |")
            appendLine("|---|---|---|---|")
            entries.forEach {
                val compare = if (it.comparable) " (=, <, >)" else ""
                appendLine(
                    "| ${label(it.labelRes)} | `${it.name}` | ${value(it.spec)}$compare | " +
                        "${firmware(FirmwareSupport.gensOf(it))} |"
                )
            }
        }
        appendLine()
        appendLine(
            "A reading the car does not answer makes the rule **not evaluable**: it does not " +
                "fire, and it does not count as false."
        )
        appendLine()
        appendLine("## Actions")
        ActionGroup.entries.forEach { group ->
            val entries = ActionType.entries.filter { it.group == group }
            if (entries.isEmpty()) return@forEach
            appendLine()
            appendLine("### ${label(group.labelRes)}")
            appendLine()
            appendLine("| Action | Entry | Asks for | When stopped only | Firmware |")
            appendLine("|---|---|---|:--:|---|")
            entries.forEach {
                val unproven = if (it.writeProven) "" else " ⚠️"
                appendLine(
                    "| ${label(it.labelRes)}$unproven | `${it.name}` | ${value(it.spec)} | " +
                        "${if (it.gated) "yes" else "—"} | ${firmware(FirmwareSupport.gensOf(it))} |"
                )
            }
        }
        appendLine()
        appendLine(
            "⚠️ — the firmware carries the property, but nothing establishes that writing it " +
                "does anything (`ActionType.writeProven`). Those actions are hidden from the " +
                "editor and refused by the executor until one is observed to work."
        )
        appendLine()
        appendLine(
            "The per-generation grid is in [firmware-matrix.md](firmware-matrix.md), generated " +
                "from the same annotations."
        )
    }

    /**
     * Regenerates the catalogue and fails if the committed copy is stale — the same contract
     * the firmware matrix has, so one test run repairs both.
     */
    @Test
    fun `the catalogue document is up to date`() {
        val generated = render()
        val file = File("../docs/catalogue.md")
        if (!file.exists() || file.readText().trim() != generated.trim()) {
            file.parentFile?.mkdirs()
            file.writeText(generated)
        }
        assertEquals(generated.trim(), file.readText().trim())
    }

    @Test
    fun `every catalogue entry has a label the document can print`() {
        // A missing string would render as "?" and publish a nameless row. The resource
        // exists at build time either way, so only this catches it.
        (ConditionType.entries.map { it.name to it.labelRes } +
            ActionType.entries.map { it.name to it.labelRes }).forEach { (name, res) ->
            assertTrue("$name has no English label", label(res) != "?" && label(res).isNotBlank())
        }
    }
}
