package com.evsuite.hardware

import com.evsuite.hardware.catalog.ConditionType
import com.evsuite.hardware.catalog.ActionType
/**
 * Generates the firmware compatibility matrix from the [SupportedOn] annotations.
 *
 * This is the single source of truth for the README table: rather than a hand-maintained
 * grid that drifts from the code, the table is rendered from the same annotations that
 * drive the runtime filter. A test writes it out and checks the README against it.
 *
 * Entry labels come from resource ids, which are not available on the JVM, so the matrix
 * uses the enum constant names — stable identifiers that also appear in the code.
 */
object FirmwareMatrix {

    /** Column order for the table. */
    private val COLUMNS = listOf(
        FirmwareGen.SWI133, FirmwareGen.SWI68, FirmwareGen.SWI165,
        FirmwareGen.SWI69, FirmwareGen.SWI131, FirmwareGen.SWI132
    )

    /** Marks an action the firmware carries but whose write was never shown to do anything. */
    private const val UNPROVEN = "⚠️"

    fun render(): String = buildString {
        appendLine("<!-- GENERATED by FirmwareMatrix.render(); do not edit by hand. -->")
        appendLine()
        appendLine(section("Conditions", ConditionType.entries.map { it.name to FirmwareSupport.gensOf(it) }))
        appendLine()
        append(section("Actions", ActionType.entries.map {
            it.name + (if (it.writeProven) "" else " $UNPROVEN") to FirmwareSupport.gensOf(it)
        }))
        // A ✅ says the firmware carries the property, which is not the same as the write
        // doing something. Without this the table promises actions the apps refuse to run.
        if (ActionType.entries.any { !it.writeProven }) {
            appendLine()
            appendLine(
                "$UNPROVEN — the firmware carries the property, but nothing establishes that " +
                    "writing it has any effect (`ActionType.writeProven`). These actions are " +
                    "hidden from the editors and refused by the executors until one is observed " +
                    "to work."
            )
        }
    }

    private fun section(title: String, rows: List<Pair<String, Set<FirmwareGen>?>>): String = buildString {
        appendLine("### $title")
        appendLine()
        appendLine("| Entry | " + COLUMNS.joinToString(" | ") { it.name } + " |")
        appendLine("|---|" + COLUMNS.joinToString("") { ":--:|" })
        // Firmware-independent entries (no annotation) are listed once, not per column.
        rows.filter { it.second == null }.forEach { (name, _) ->
            appendLine("| $name | " + COLUMNS.joinToString(" | ") { "—" } + " |")
        }
        rows.filter { it.second != null }.forEach { (name, gens) ->
            val cells = COLUMNS.joinToString(" | ") { if (it in gens!!) "✅" else "❌" }
            appendLine("| $name | $cells |")
        }
    }
}
